// 首版界面文案，与 Web 的中英文设置保持一致。
class AppText {
  const AppText(this.language);

  final String language;

  // 返回当前语言的界面文案；未知键返回键名以便定位遗漏。
  String get(String key) {
    const zh = <String, String>{
      'map': '地图',
      'discover': '发现',
      'charts': '排行榜',
      'settings': '设置',
      'searchHint': '搜索电台、语言或流派',
      'trending': '全球热门',
      'global': '全球',
      'byLanguage': '按语言',
      'byGenre': '按流派',
      'preferences': '偏好设置',
      'language': '语言',
      'theme': '外观',
      'system': '跟随系统',
      'light': '浅色',
      'dark': '深色',
      'about': '关于 WorldTuner',
      'retry': '重试',
      'empty': '没有找到电台',
      'loadError': '加载失败，请重试',
      'loading': '正在加载…',
      'noStation': '选择一个电台开始收听',
      'playing': '正在播放',
      'paused': '已暂停',
      'buffering': '正在缓冲',
      'audioError': '播放失败，请更换电台或重试',
      'apiMissing': '未配置 API_BASE_URL',
      'apiMissingHelp': '启动时通过 --dart-define=API_BASE_URL 指定 API 服务地址。',
      'mapKeyMissing': '未配置地图密钥，暂不显示卫星底图',
      'mapLoading': '正在载入地图点位…',
      'mapError': '地图点位加载失败',
      'station': '电台',
      'country': '国家',
      'languageField': '语言',
      'codec': '格式',
      'votes': '票数',
      'unknown': '未知',
      'english': 'English',
      'chinese': '简体中文',
      'online': '网络电台',
      'profile': '我的',
      'globe': '地球',
      'all': '全部',
      'genres': '音乐流派',
      'countries': '国家/地区',
      'languages': '多语言频道',
      'stations': '电台',
      'editorPick': '精选电台',
      'popularStations': '热门电台',
      'globalCharts': '全球电台排行榜',
      'weeklyCharts': '按票数排序，探索全球热门声音',
      'topStations': '榜单列表',
      'favorites': '收藏电台',
      'history': '最近收听',
      'appearance': '外观与主题',
      'audioSettings': '音频与播放',
      'localization': '语言设置',
      'aboutApp': '关于应用',
      'darkMode': '深色模式',
      'lightMode': '日间模式',
      'followSystem': '跟随系统',
      'searchStations': '搜索电台、语言、流派…',
      'live': '直播',
      'listenNow': '立即收听',
      'chooseGenre': '按流派探索',
      'noFavorites': '还没有收藏电台',
      'noHistory': '最近还没有播放记录',
      'localOnly': '数据仅保存在当前设备',
      'stationCount': '个电台',
      'mapHint': '探索全球电台',
      'loadingStation': '正在获取电台详情…',
      'tapStation': '点击地图标记，发现当地声音',
      'voteCount': '票',
      'bitrate': '码率',
      'filterAll': '全球总榜',
      'filterLanguage': '语言榜',
      'filterGenre': '流派榜',
      'clearSearch': '清除搜索',
      'refresh': '刷新',
      'play': '播放',
      'pause': '暂停',
    };
    const en = <String, String>{
      'map': 'Map',
      'discover': 'Discover',
      'charts': 'Charts',
      'settings': 'Settings',
      'searchHint': 'Search stations, languages, or genres',
      'trending': 'Trending Worldwide',
      'global': 'Global',
      'byLanguage': 'By language',
      'byGenre': 'By genre',
      'preferences': 'Preferences',
      'language': 'Language',
      'theme': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'about': 'About WorldTuner',
      'retry': 'Retry',
      'empty': 'No stations found',
      'loadError': 'Could not load stations',
      'loading': 'Loading…',
      'noStation': 'Choose a station to listen',
      'playing': 'Playing',
      'paused': 'Paused',
      'buffering': 'Buffering',
      'audioError': 'Playback failed. Try another station or retry.',
      'apiMissing': 'API_BASE_URL is missing',
      'apiMissingHelp':
          'Pass --dart-define=API_BASE_URL when starting the app.',
      'mapKeyMissing': 'Map key is missing; satellite tiles are unavailable',
      'mapLoading': 'Loading map stations…',
      'mapError': 'Could not load map stations',
      'station': 'Station',
      'country': 'Country',
      'languageField': 'Language',
      'codec': 'Codec',
      'votes': 'Votes',
      'unknown': 'Unknown',
      'english': 'English',
      'chinese': '简体中文',
      'online': 'Internet radio',
      'profile': 'Profile',
      'globe': 'Globe',
      'all': 'All',
      'genres': 'Genres',
      'countries': 'Countries',
      'languages': 'Languages',
      'stations': 'stations',
      'editorPick': "Editor's pick",
      'popularStations': 'Trending stations',
      'globalCharts': 'Global radio charts',
      'weeklyCharts': 'Discover popular stations by vote count',
      'topStations': 'Top stations',
      'favorites': 'Favorite stations',
      'history': 'Recently played',
      'appearance': 'Appearance & theme',
      'audioSettings': 'Audio & playback',
      'localization': 'Language',
      'aboutApp': 'About the app',
      'darkMode': 'Dark mode',
      'lightMode': 'Light mode',
      'followSystem': 'Use system setting',
      'searchStations': 'Search stations, languages, genres…',
      'live': 'Live',
      'listenNow': 'Listen now',
      'chooseGenre': 'Explore by genre',
      'noFavorites': 'No favorite stations yet',
      'noHistory': 'No listening history yet',
      'localOnly': 'Stored on this device only',
      'stationCount': 'stations',
      'mapHint': 'Explore stations worldwide',
      'loadingStation': 'Loading station details…',
      'tapStation': 'Tap a map pin to hear a local station',
      'voteCount': 'votes',
      'bitrate': 'Bitrate',
      'filterAll': 'Global top',
      'filterLanguage': 'Languages',
      'filterGenre': 'Genres',
      'clearSearch': 'Clear search',
      'refresh': 'Refresh',
      'play': 'Play',
      'pause': 'Pause',
    };
    return (language == 'zh' ? zh : en)[key] ?? key;
  }
}
