// 首版界面文案，与 Web 的中英文设置保持一致。
class AppText {
  const AppText(this.language);

  final String language;

  // 返回当前语言的界面文案；未知键返回键名以便定位遗漏。
  String get(String key) {
    const zh = <String, String>{
      'map': '地图',
      'discover': '发现',
      'charts': '排行榜',
      'settings': '设置',
      'searchHint': '搜索电台、语言或流派',
      'trending': '全球热门',
      'global': '全球',
      'byLanguage': '按语言',
      'byGenre': '按流派',
      'preferences': '偏好设置',
      'language': '语言',
      'theme': '外观',
      'system': '跟随系统',
      'light': '浅色',
      'dark': '深色',
      'about': '关于 worldTuner',
      'retry': '重试',
      'empty': '没有找到电台',
      'loadError': '加载失败，请重试',
      'loading': '正在加载…',
      'noStation': '选择一个电台开始收听',
      'playing': '正在播放',
      'paused': '已暂停',
      'buffering': '正在缓冲',
      'audioError': '播放失败，请更换电台或重试',
      'apiMissing': '未配置 API_BASE_URL',
      'apiMissingHelp': '启动时通过 --dart-define=API_BASE_URL 指定 API 服务地址。',
      'mapKeyMissing': '未配置地图密钥，暂不显示 3D 地球',
      'mapLoading': '正在载入地图点位…',
      'mapError': '地图点位加载失败',
      'station': '电台',
      'country': '国家',
      'languageField': '语言',
      'codec': '格式',
      'votes': '票数',
      'unknown': '未知',
      'english': 'English',
      'chinese': '简体中文',
      'online': '网络电台',
      'profile': '我的',
      'globe': '地球',
      'all': '全部',
      'genres': '音乐流派',
      'countries': '国家/地区',
      'languages': '多语言频道',
      'stations': '电台',
      'editorPick': '精选电台',
      'popularStations': '热门电台',
      'globalCharts': '全球电台排行榜',
      'weeklyCharts': '按票数排序，探索全球热门声音',
      'topStations': '榜单列表',
      'favorites': '收藏电台',
      'history': '最近收听',
      'appearance': '外观与主题',
      'audioSettings': '音频与播放',
      'localization': '语言设置',
      'aboutApp': '关于应用',
      'darkMode': '深色模式',
      'lightMode': '日间模式',
      'followSystem': '跟随系统',
      'searchStations': '搜索电台、语言、流派…',
      'searchExample': '搜索电台、国家、语言…',
      'back': '返回',
      'filterOptions': '筛选选项',
      'bestMatch': '最佳匹配',
      'matchingStations': '匹配电台频段',
      'sortPopular': '排序: 热门程度',
      'moreActions': '更多操作',
      'live': '直播',
      'listenNow': '立即收听',
      'chooseGenre': '按流派探索',
      'noFavorites': '还没有收藏电台',
      'noHistory': '最近还没有播放记录',
      'localOnly': '数据仅保存在当前设备',
      'stationCount': '个电台',
      'mapHint': '探索全球电台',
      'loadingStation': '正在获取电台详情…',
      'tapStation': '点击地图标记，发现当地声音',
      'voteCount': '票',
      'bitrate': '码率',
      'filterAll': '全球总榜',
      'filterLanguage': '语言榜',
      'filterGenre': '流派榜',
      'clearSearch': '清除搜索',
      'refresh': '刷新',
      'play': '播放',
      'pause': '暂停',
      'entryStatus': '全球电台探索中',
      'goToLogin': '去登录',
      'entryTitleFirst': '聆听全球频率',
      'entryTitleSecond': '触碰声音经纬',
      'entrySubtitle': '跨越地域边界，发现世界各地的真实电台',
      'entryFeatureTitle': '探索全球电台',
      'entryFeatureSubtitle': '选择声音，随时开始收听',
      'registerWithContact': '使用手机号 / 邮箱注册',
      'wechat': '微信',
      'passwordLogin': '账号密码登录',
      'registerNewAccount': '立即注册新电台号',
      'exploreAsGuest': '先以访客身份探索地球',
      'entryPrivacyNote': '当前版本无需账号；收藏和收听记录只保存在本机。',
      'registrationUnavailable': '注册功能尚未开放，可通过“去登录”进入应用。',
      'vipMenu': '查看 VIP 权益',
      'vipComingSoon': '功能规划中 · 即将推出',
      'vipEyebrow': 'worldTuner VIP · 即将推出',
      'vipHeroFirst': '让世界的声音，',
      'vipHeroSecond': '跟着你的生活走。',
      'vipHeroDescription': '收藏随行，按心情整理，让喜爱的电台在对的时间响起。',
      'vipSync': '跨设备同步',
      'vipGroups': '专属收听空间',
      'vipSchedule': '定时收听',
      'vipSample': '示例数据',
      'vipSampleStation': 'Paris Jazz Club',
      'vipSampleDescription': '巴黎 · 设定 07:30 晨间唤醒伴随',
      'vipSampleStatus': '功能规划示意',
      'vipBenefitsAction': '了解会员权益',
      'vipFreeAction': '继续免费探索世界电台',
      'vipConceptNote': '当前为概念规划；地图、搜索与基础收听始终免费。',
      'vipBenefitsTitle': '核心权益规划',
      'vipPlanned': '即将支持',
      'vipBenefitOneLabel': '权益 01 · 收藏随行',
      'vipBenefitOneTitle': '从这台设备收藏，下次打开仍是熟悉的频率。',
      'vipBenefitOneDescription': '计划让收藏与收听记录在你的设备间同步，换设备也能接着听。',
      'vipBenefitOnePreview': '收藏电台 · 多设备同步示意',
      'vipBenefitTwoLabel': '权益 02 · 轻松整理',
      'vipBenefitTwoTitle': '为通勤、工作和深夜，各留一个声音空间。',
      'vipBenefitTwoDescription': '计划按场景与心情创建专属分组，整理常听的城市、流派和电台。',
      'vipBenefitTwoPreview': '早间通勤 · 专注工作 · 深夜静听',
      'vipBenefitThreeLabel': '权益 03 · 按时收听',
      'vipBenefitThreeTitle': '早晨醒来，或夜晚放松，让电台准时陪伴。',
      'vipBenefitThreeDescription': '计划提供电台闹钟和定时播放，按你设置的时间开始收听。',
      'vipBenefitThreePreview': '07:30 · 工作日晨间唤醒示意',
      'vipCompareTitle': '清晰坦诚的权益分工',
      'vipCompareDescription': '免费版本始终完整支持全球电台的探索与聆听。',
      'vipFreeTitle': '免费探索版',
      'vipFreeStatus': '完全开放',
      'vipFreeFeatureOne': '3D 地球漫游',
      'vipFreeFeatureTwo': '全球电台完整收听',
      'vipFreeFeatureThree': '全局搜索与流派榜单',
      'vipFreeFeatureFour': '本地电台收藏记录',
      'vipFreeFooter': '始终对所有人免费',
      'vipPremiumTitle': 'VIP 进阶版',
      'vipPremiumStatus': '规划中',
      'vipPremiumFeatureOne': '换设备继续听（云同步）',
      'vipPremiumFeatureTwo': '自定义收听场景空间',
      'vipPremiumFeatureThree': '电台闹钟与计划收听',
      'vipPlansTitle': '未来的计划结构',
      'vipPlansDescription': '正式上线前将公布完整价格与订阅规则。',
      'vipMonthly': '月度会员',
      'vipYearly': '年度会员',
      'vipPricePending': '价格待公布',
      'vipFaqTitle': '常见疑问解答',
      'vipFaqOneQuestion': '不订阅 VIP 还能正常听电台吗？',
      'vipFaqOneAnswer': '可以。地球探索、搜索、榜单、播放和本地收藏始终免费。',
      'vipFaqTwoQuestion': 'VIP 什么时候正式推出？',
      'vipFaqTwoAnswer': '尚未公布推出日期，目前没有可购买的会员方案。',
      'vipFaqThreeQuestion': '现有的本地收藏会丢失吗？',
      'vipFaqThreeAnswer': '不会。本地收藏仍保存在当前设备；未来的同步迁移规则会另行说明。',
      'vipClosing': '世界很大，喜欢的声音值得好好收藏。',
      'vipExploreAction': '继续探索电台',
    };
    const en = <String, String>{
      'map': 'Map',
      'discover': 'Discover',
      'charts': 'Charts',
      'settings': 'Settings',
      'searchHint': 'Search stations, languages, or genres',
      'trending': 'Trending Worldwide',
      'global': 'Global',
      'byLanguage': 'By language',
      'byGenre': 'By genre',
      'preferences': 'Preferences',
      'language': 'Language',
      'theme': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'about': 'About worldTuner',
      'retry': 'Retry',
      'empty': 'No stations found',
      'loadError': 'Could not load stations',
      'loading': 'Loading…',
      'noStation': 'Choose a station to listen',
      'playing': 'Playing',
      'paused': 'Paused',
      'buffering': 'Buffering',
      'audioError': 'Playback failed. Try another station or retry.',
      'apiMissing': 'API_BASE_URL is missing',
      'apiMissingHelp':
          'Pass --dart-define=API_BASE_URL when starting the app.',
      'mapKeyMissing': 'Map key is missing; the 3D globe is unavailable',
      'mapLoading': 'Loading map stations…',
      'mapError': 'Could not load map stations',
      'station': 'Station',
      'country': 'Country',
      'languageField': 'Language',
      'codec': 'Codec',
      'votes': 'Votes',
      'unknown': 'Unknown',
      'english': 'English',
      'chinese': '简体中文',
      'online': 'Internet radio',
      'profile': 'Profile',
      'globe': 'Globe',
      'all': 'All',
      'genres': 'Genres',
      'countries': 'Countries',
      'languages': 'Languages',
      'stations': 'stations',
      'editorPick': "Editor's pick",
      'popularStations': 'Trending stations',
      'globalCharts': 'Global radio charts',
      'weeklyCharts': 'Discover popular stations by vote count',
      'topStations': 'Top stations',
      'favorites': 'Favorite stations',
      'history': 'Recently played',
      'appearance': 'Appearance & theme',
      'audioSettings': 'Audio & playback',
      'localization': 'Language',
      'aboutApp': 'About the app',
      'darkMode': 'Dark mode',
      'lightMode': 'Light mode',
      'followSystem': 'Use system setting',
      'searchStations': 'Search stations, languages, genres…',
      'searchExample': 'Search stations, countries, languages…',
      'back': 'Back',
      'filterOptions': 'Filters',
      'bestMatch': 'Best match',
      'matchingStations': 'Matching stations',
      'sortPopular': 'Sort: Popular',
      'moreActions': 'More actions',
      'live': 'Live',
      'listenNow': 'Listen now',
      'chooseGenre': 'Explore by genre',
      'noFavorites': 'No favorite stations yet',
      'noHistory': 'No listening history yet',
      'localOnly': 'Stored on this device only',
      'stationCount': 'stations',
      'mapHint': 'Explore stations worldwide',
      'loadingStation': 'Loading station details…',
      'tapStation': 'Tap a map pin to hear a local station',
      'voteCount': 'votes',
      'bitrate': 'Bitrate',
      'filterAll': 'Global top',
      'filterLanguage': 'Languages',
      'filterGenre': 'Genres',
      'clearSearch': 'Clear search',
      'refresh': 'Refresh',
      'play': 'Play',
      'pause': 'Pause',
      'entryStatus': 'EXPLORE GLOBAL RADIO',
      'goToLogin': 'Log in',
      'entryTitleFirst': 'Hear the world',
      'entryTitleSecond': 'Find your frequency',
      'entrySubtitle': 'Discover real radio stations from around the world',
      'entryFeatureTitle': 'Explore global radio',
      'entryFeatureSubtitle': 'Pick a station and start listening',
      'registerWithContact': 'Sign up with phone or email',
      'wechat': 'WeChat',
      'passwordLogin': 'Log in with password',
      'registerNewAccount': 'Create an account',
      'exploreAsGuest': 'Explore as a guest',
      'entryPrivacyNote':
          'No account is needed yet. Favorites and history stay on this device.',
      'registrationUnavailable':
          'Sign-up is not available yet. Tap Log in to enter the app.',
      'vipMenu': 'View VIP benefits',
      'vipComingSoon': 'Planned features · Coming soon',
      'vipEyebrow': 'worldTuner VIP · Coming soon',
      'vipHeroFirst': 'Let the sounds of the world',
      'vipHeroSecond': 'follow your day.',
      'vipHeroDescription':
          'Keep favorites close, organize by mood, and listen at the right time.',
      'vipSync': 'Sync across devices',
      'vipGroups': 'Listening spaces',
      'vipSchedule': 'Scheduled listening',
      'vipSample': 'Example',
      'vipSampleStation': 'Paris Jazz Club',
      'vipSampleDescription': 'Paris · Morning listening at 07:30',
      'vipSampleStatus': 'Concept preview',
      'vipBenefitsAction': 'Explore VIP benefits',
      'vipFreeAction': 'Keep exploring radio for free',
      'vipConceptNote':
          'This is a concept. Maps, search, and basic listening stay free.',
      'vipBenefitsTitle': 'Planned core benefits',
      'vipPlanned': 'Coming soon',
      'vipBenefitOneLabel': 'BENEFIT 01 · FAVORITES ANYWHERE',
      'vipBenefitOneTitle': 'Find your familiar stations on another device.',
      'vipBenefitOneDescription':
          'We plan to sync favorites and history across your devices.',
      'vipBenefitOnePreview': 'Favorite stations · Device sync preview',
      'vipBenefitTwoLabel': 'BENEFIT 02 · STAY ORGANIZED',
      'vipBenefitTwoTitle': 'Make room for commutes, focus, and late nights.',
      'vipBenefitTwoDescription':
          'We plan custom groups for the cities, genres, and stations you love.',
      'vipBenefitTwoPreview': 'Morning commute · Focus · Late night',
      'vipBenefitThreeLabel': 'BENEFIT 03 · LISTEN ON TIME',
      'vipBenefitThreeTitle': 'Let a station join your morning or evening.',
      'vipBenefitThreeDescription':
          'We plan radio alarms and playback at times you choose.',
      'vipBenefitThreePreview': '07:30 · Weekday alarm preview',
      'vipCompareTitle': 'A clear split of benefits',
      'vipCompareDescription':
          'Exploring and listening to global radio stays free for everyone.',
      'vipFreeTitle': 'Free exploration',
      'vipFreeStatus': 'Available now',
      'vipFreeFeatureOne': '3D globe exploration',
      'vipFreeFeatureTwo': 'Full station listening',
      'vipFreeFeatureThree': 'Search and charts',
      'vipFreeFeatureFour': 'Local favorites',
      'vipFreeFooter': 'Always free for everyone',
      'vipPremiumTitle': 'VIP extras',
      'vipPremiumStatus': 'Planned',
      'vipPremiumFeatureOne': 'Continue across devices',
      'vipPremiumFeatureTwo': 'Custom listening spaces',
      'vipPremiumFeatureThree': 'Radio alarms and schedules',
      'vipPlansTitle': 'Future plans',
      'vipPlansDescription':
          'Full pricing and subscription terms will be published before launch.',
      'vipMonthly': 'Monthly membership',
      'vipYearly': 'Annual membership',
      'vipPricePending': 'Price to be announced',
      'vipFaqTitle': 'Frequently asked questions',
      'vipFaqOneQuestion': 'Can I still listen without VIP?',
      'vipFaqOneAnswer':
          'Yes. The globe, search, charts, playback, and local favorites stay free.',
      'vipFaqTwoQuestion': 'When will VIP launch?',
      'vipFaqTwoAnswer':
          'No launch date has been announced. There is nothing to purchase yet.',
      'vipFaqThreeQuestion': 'Will I lose my local favorites?',
      'vipFaqThreeAnswer':
          'No. They stay on this device. Future sync migration rules will be shared later.',
      'vipClosing': 'The world is vast. Keep the sounds you love close.',
      'vipExploreAction': 'Explore radio',
    };
    return (language == 'zh' ? zh : en)[key] ?? key;
  }
}
